apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: seonho-test
  name: service-broker-role
rules:
- apiGroups: ["tmax.io"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
